In [1]:
import pandas as pd

In [9]:
#Load USDA database & transform it into the form we need
food_database = pd.read_excel("2019-2020 FNDDS At A Glance - FNDDS Nutrient Values.xlsx", 
                              header = 1 #set column headers
                              )


Food code                     Main food description  \
0      11000000                               Milk, human   
1      11100000                                 Milk, NFS   
2      11111000                               Milk, whole   
3      11112110                    Milk, reduced fat (2%)   
4      11112210                        Milk, low fat (1%)   
...         ...                                       ...   
5619   99997802          Tomatoes as ingredient in omelet   
5620   99997804  Other vegetables as ingredient in omelet   
5621   99997810         Vegetables as ingredient in curry   
5622   99998130         Sauce as ingredient in hamburgers   
5623   99998210      Industrial oil as ingredient in food   

      WWEIA Category number       WWEIA Category description  Energy (kcal)  \
0                      9602                       Human milk             70   
1                      1004                Milk, reduced fat             52   
2                      1002                      Milk, whole             61   
3                      1004                Milk, reduced fat             50   
4                      1006                     Milk, lowfat             43   
...                     ...                              ...            ...   
5619                   9999  Not included in a food category             25   
5620                   9999  Not included in a food category             39   
5621                   9999  Not included in a food category             52   
5622                   9999  Not included in a food category            272   
5623                   9999  Not included in a food category            892   

      Protein (g)  Carbohydrate (g)  Sugars, total\n(g)  \
0            1.03              6.89                6.89   
1            3.33              4.83                4.88   
2            3.27              4.63                4.81   
3            3.36              4.90                4.89   
4            3.38              5.18                4.96   
...           ...               ...                 ...   
5619         1.11              5.48                3.42   
5620         3.25              5.74                2.73   
5621         1.81             11.60                3.25   
5622         1.34             17.14               13.08   
5623         0.00              0.00                0.00   

      Fiber, total dietary (g)  Total Fat (g)  ...  20:1\n(g)  22:1\n(g)  \
0                          0.0           4.38  ...      0.040      0.000   
1                          0.0           2.14  ...      0.002      0.000   
2                          0.0           3.20  ...      0.004      0.000   
3                          0.0           1.90  ...      0.002      0.000   
4                          0.0           0.95  ...      0.001      0.000   
...                        ...            ...  ...        ...        ...   
5619                       1.6           0.23  ...      0.000      0.000   
5620                       1.4           0.39  ...      0.000      0.000   
5621                       2.2           0.19  ...      0.000      0.000   
5622                       0.6          22.85  ...      0.106      0.133   
5623                       0.0         100.00  ...      0.322      0.024   

      18:2\n(g)  18:3\n(g)  18:4\n(g)  20:4\n(g)  20:5 n-3\n(g)  \
0         0.374      0.052        0.0      0.026          0.000   
1         0.074      0.008        0.0      0.003          0.000   
2         0.115      0.013        0.0      0.004          0.001   
3         0.061      0.007        0.0      0.003          0.000   
4         0.033      0.004        0.0      0.001          0.000   
...         ...        ...        ...        ...            ...   
5619      0.089      0.004        0.0      0.000          0.000   
5620      0.174      0.001        0.0      0.000          0.000   
5621      0.052      0.012        0.0      0.000          0.000   
5622     11.810      1.682      

Current thought:
- amount of foods are inputs
- quality rates are weights (e.g., amount of calories per 100gs)

In [9]:
import numpy as np
#deriv wrt amounts is quality rate

amounts = np.array([[1.0,1.0]])

#rows represent food, cols represent qualities
quality_rates = np.array([[1,5,2],
                          [2,1,6]])

targets = [5,10,8]

output = np.dot(amounts, quality_rates)

#squared error is the loss function
error = (output - targets)**2

print("Output:")
print(output)
print("Error:")
print(error)

Output:
[[3. 6. 8.]]
Error:
[[ 4. 16.  0.]]


In [10]:
#derivative of loss wrt to output
dloss = 2*output
print(dloss)

dmax = targets.copy
dmax = np.ones_like(output)
dmax[output >= targets] = 0 
print(dmax)

dfoods = dloss * dmax
print(dfoods)

dinputs = np.dot(dfoods, quality_rates.T)
print(dinputs)

learning_rate = .01

amounts += learning_rate * dinputs
print(amounts)

[[ 6. 12. 16.]]
[[1. 1. 0.]]
[[ 6. 12.  0.]]
[[66. 24.]]
[[1.66 1.24]]


In [34]:
#very basic prototype optimization algorithm

import numpy as np
import matplotlib.pyplot as plt

#intialzie amounts
amounts = np.array([[1.0,1.0]])

#rows represent food, cols represent qualities
quality_rates = np.array([[3,2,.5],
                          [1,2,2]])

learning_rate = .001

#goal amounts
targets = [5,10,8]

outputs, errors, amountss = [], [], []

stop_time = 1000
for i in range(stop_time):
    output = np.dot(amounts, quality_rates)
    outputs.append(output)
    #squared error is the loss function
    error = (output - targets)**2
    errors.append(error)
    #derivative of loss wrt to output
    dloss = 2*output
    #print(dloss)

    dmax = targets.copy
    dmax = np.ones_like(output)
    dmax[output >= targets] = 0 
    #print(dmax)

    dfoods = dloss * dmax
    #print(dfoods)

    #deriv wrt amounts is quality rate
    dinputs = np.dot(dfoods, quality_rates.T)
    #print(dinputs)

    amounts += learning_rate * dinputs
    amountss.append(amounts)


print(amounts)
print(output)
print(error)

[[2.51039082 3.37482759]]
[[10.90600006 11.77043683  8.0048506 ]]
[[3.48808367e+01 3.13444658e+00 2.35283144e-05]]
